---
documentclass: ctexart
output:
  rticles::ctex:
    fig_caption: yes
    number_sections: yes
    toc: yes
    template: template.tex
classoption: "hyperref,"
geometry: margin=1in
header-includes:
   - \usepackage{graphicx}
   - \usepackage{float}
   - \usepackage{indentfirst}
   - \setlength{\parindent}{4em}
logo: "cufe.jpg"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(Matrix)
library(glmnet)
library(formattable)
library(tidyverse)
library(knitr)
# library(reticulate)
# use_condaenv(conda = "/usr/local/anaconda3/bin/conda")
# use_python("/usr/local/anaconda3/bin/python3.8")
# py_config()
```

\newpage

# Introduction

This document contains definitions of all the functions as well as a test case for the algorithm in the end of the article.

[Here is the source file for the algorithm on github.](https://github.com/wuyuchong/glm_lasso)

# Comparison for glm_lasso and glmnet

```{r}
compare = function(rho, n, p, gamma = 3, pmax = 9)
{
  for(i in 1:10)
  {
    # Data Simulation
    source("main.R")
    family = "logit"
    s = 6
    beta_0 = c(0.05, 3, -2.5, 3.5, -1.5, -3)
    beta_1 = rep(0, p - s)
    beta = c(beta_0, beta_1)
    sim = sim_data(beta, rho, n, family)
    x = sim[[1]]
    y = sim[[2]]
    
    # Time Comparison
    t = NULL
    
    t1 = Sys.time()
    model_lasso = logit_lasso(x, y, pmax = pmax)
    t2 = Sys.time()
    t = c(t, t2 - t1)
    
    t1 = Sys.time()
    model_glmnet = glmnet(x, y, family = "binomial", pmax = pmax)
    t2 = Sys.time()
    t = c(t, t2 - t1)
    
    # Recall and Precision
    recall = NULL
    precision = NULL
    
    if(model_lasso[[4]] == pmax)
    {
      b_lasso = model_lasso[[1]]
      is_active_lasso = model_lasso[[2]]
      recall = c(recall, sum(is_active_lasso[1:6]) / 6)
      precision = c(precision, sum(is_active_lasso[1:6]) / (pmax + 1))   
    } else
    {
      next
    }
    
    if(model_glmnet$df[length(model_glmnet$df)] == pmax)
    {
      temp = coef(model_glmnet, s = model_glmnet$lambda[length(model_glmnet$lambda)])
      recall = c(recall, sum(temp[1:6] != 0) / 6)
      precision = c(precision, sum(temp[1:6] != 0) / (pmax + 1))   
    } else
    {
      next
    }
    
    return(cbind(t, recall, precision))
  }
  print("Can not find outcome, try another time please.")
}

trans = function(variable, name, percent = FALSE)
{
  variable = as.data.frame(variable)
  rownames(variable) = c("glm_lasso", "glmnet")
  names(variable) = name
  return(variable)
}
model_glmnet
```

## For rho

n = 400, p = 1000, pmax = 9

```{r cache=TRUE, include=FALSE}
time_rho = NULL
recall_rho = NULL
precision_rho = NULL
for(rho in c(0.1, 0.3, 0.5, 0.7, 0.9))
{
  model = compare(rho = rho, n = 400, p = 1000, gamma = 3, pmax = 9)
  time_rho = cbind(time_rho, model[,1])
  recall_rho = cbind(recall_rho, model[,2])
  precision_rho = cbind(precision_rho, model[,3])
}
name_rho = c("rho = 0.1", "rho = 0.3", "rho = 0.5", "rho = 0.7", "rho = 0.9")
```

```{r}
kable(trans(time_rho, name_rho), digit = 2, caption = "Time consuming - Comparison for two models when rho is changed")
```

```{r}
kable(trans(recall_rho, name_rho), digit = 2, caption = "Recall - Comparison for two models when rho is changed")
```

```{r}
kable(trans(precision_rho, name_rho), digit = 2, caption = "Precision - Comparison for two models when rho is changed")
```

\newpage

## For n

rho = 0.5, p = 1000, pmax = 9

```{r cache=TRUE, include=FALSE}
time_n = NULL
recall_n = NULL
precision_n = NULL
for(n in c(200, 400, 800, 1600, 3200))
{
  model = compare(rho = 0.5, n = n, p = 1000, gamma = 3, pmax = 9)
  time_n = cbind(time_n, model[,1])
  recall_n = cbind(recall_n, model[,2])
  precision_n = cbind(precision_n, model[,3])
}
name_n = c("n = 200", "n = 400", "n = 800", "n = 1600", "n = 3200")
```

```{r}
model = compare(rho = 0.5, n = 10000, p = 1000, gamma = 3, pmax = 9)
```


```{r}
kable(trans(time_n, name_n), digit = 2, caption = "Time consuming - Comparison for two models when n is changed")
```

```{r}
kable(trans(recall_n, name_n), digit = 2, caption = "Recall - Comparison for two models when n is changed")
```

```{r}
kable(trans(precision_n, name_n), digit = 2, caption = "Precision - Comparison for two models when n is changed")
```

\newpage

## For p

rho = 0.5, n = 400, pmax = 9

```{r cache=TRUE, include=FALSE}
time_p = NULL
recall_p = NULL
precision_p = NULL
for(p in c(50, 100, 250, 500, 1000))
{
  model = compare(rho = 0.5, n = 400, p = p, gamma = 3, pmax = 9)
  time_p = cbind(time_p, model[,1])
  recall_p = cbind(recall_p, model[,2])
  precision_p = cbind(precision_p, model[,3])
}
name_p = c("p = 50", "p = 100", "p = 250", "p = 500", "p = 1000")
```

```{r}
kable(trans(time_p, name_p), digit = 2, caption = "Time consuming - Comparison for two models when p is changed")
```

```{r}
kable(trans(recall_p, name_p), digit = 2, caption = "Recall - Comparison for two models when p is changed")
```

```{r}
kable(trans(precision_p, name_p), digit = 2, caption = "Precision - Comparison for two models when p is changed")
```

\newpage

## For pmax

rho = 0.5, n = 400, p = 1000

```{r cache=TRUE, include=FALSE}
time_pmax = NULL
recall_pmax = NULL
precision_pmax = NULL
for(pmax in c(2, 4, 6, 8, 10))
{
  model = compare(rho = 0.5, n = 400, p = 1000, gamma = 3, pmax = pmax)
  time_pmax = cbind(time_pmax, model[,1])
  recall_pmax = cbind(recall_pmax, model[,2])
  precision_pmax = cbind(precision_pmax, model[,3])
}
name_pmax = c("pmax = 2", "pmax = 4", "pmax = 8", "pmax = 16", "pmax = 32")
```

```{r}
kable(trans(time_pmax, name_pmax), digit = 2, caption = "Time consuming - Comparison for two models when pmax is changed")
```

```{r}
kable(trans(recall_pmax, name_pmax), digit = 2, caption = "Recall - Comparison for two models when pmax is changed")
```

```{r}
kable(trans(precision_pmax, name_pmax), digit = 2, caption = "Precision - Comparison for two models when pmax is changed")
```



# Fit

```{r}
family = "logit"
rho = 0.5
n = 400
p = 1000 
s = 6
pmax = 10
beta_0 = c(0.05, 3, -2.5, 3.5, -1.5, -3)
beta_1 = rep(0, p - s)
beta = c(beta_0, beta_1)
sim = sim_data(beta, rho, n, family)
x = sim[[1]]
y = sim[[2]]

model = logit_lasso(x, y, pmax=10)
b = model[[1]]
is_active = model[[2]]
lamb = model[[3]]
df = model[[4]]

print(b[1:10])
print(lamb)
```

```{r}
model_glmnet = glmnet(x, y, family = "binomial", pmax = 10)
print(model_glmnet)
coef(model_glmnet, s = 0.04625)
```

